---
abstract: 'A POE-based parser for the IRC protocol.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-IRCD
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Filter::IRCD:
    file: lib/POE/Filter/IRCD.pm
    version: 2.42
requires:
  POE: 0.3202
  POE::Filter: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-filter-ircd/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-filter-ircd.git
version: 2.42
