# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-IRCD
version:      1.1
version_from: lib/POE/Filter/IRCD.pm
installdirs:  site
requires:
    POE:                           0.0607

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
