---
abstract: 'A POE-based parser for the IRC protocol'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-IRCD
requires:
  POE: 0.3202
  POE::Filter: 0
  perl: 5.006
resources:
  homepage: https://github.com/bingos/poe-filter-ircd
  repository: https://github.com/bingos/poe-filter-ircd.git
version: 2.44
