---
abstract: 'A POE-based parser for the IRC protocol.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.73'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Filter-IRCD
no_index:
  directory:
    - inc
    - t
    - examples
    - examples
requires:
  POE: 0.3202
  POE::Filter: 0
  perl: 5.6.0
version: 2.38
